// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trading.DataAccess;

#nullable disable

namespace Trading.DataAccess.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260812154349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trading.Core.Models.SymbolPriceState", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Symbol");

                    b.Property<decimal>("AskPrice")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("AskPrice");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("BidPrice");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("CurrentMarketPrice");

                    b.Property<decimal>("Spread")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("Spread");

                    b.Property<decimal>("SpreadPercent")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("SpreadPercent");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.HasKey("Symbol");

                    b.ToTable("SymbolPrices", "dbo");
                });

            modelBuilder.Entity("Trading.Core.Models.TradeOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ClientOrderId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("Price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(22, 6)")
                        .HasColumnName("Quantity");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("RejectionReason");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Side");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Symbol");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Orders", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
